from .models import Category


UI_TRANSLATIONS = {
    'ru': {
        'free_delivery': '📦 Бесплатная доставка от 5000₸',
        'working_hours': 'Пн-Вс 9:00–21:00',
        'search_placeholder': 'Найти товары, бренды, категории...',
        'ai_assistant': 'AI Помощник',
        'ai_chat': 'AI Чат',
        'wishlist': 'Избранное',
        'cart': 'Корзина',
        'profile': 'Профиль',
        'orders': 'Мои заказы',
        'logout': 'Выйти',
        'login': 'Войти',
        'all_products': 'Все товары',
        'footer_about': 'Крупнейший маркетплейс с миллионами товаров и быстрой доставкой по всему Казахстану',
        'buyers': 'Покупателям',
        'catalog': 'Каталог товаров',
        'company': 'Компания',
        'about': 'О нас',
        'partners': 'Партнёрам',
        'jobs': 'Вакансии',
        'contacts': 'Контакты',
        'support': 'Поддержка',
        'free_call': 'Бесплатно, Пн-Вс 9–21',
        'rights': '© 2026 YMarket. Все права защищены.',
        'privacy': 'Политика конфиденциальности',
        'terms': 'Пользовательское соглашение',
        'home_title': 'Главная',
        'sale_badge': '🔥 Мегараспродажа до -70%',
        'hero_title_1': 'Всё что нужно',
        'hero_title_2': '— здесь и сейчас',
        'hero_text': 'Миллионы товаров, быстрая доставка, лучшие цены. Найди что ищешь с нашим AI-ассистентом.',
        'view_catalog': 'Смотреть каталог →',
        'ask_ai': '🤖 Спросить AI',
        'products_short': 'товаров',
        'delivery_short': 'доставка',
        'buyers_short': 'покупателей',
        'your_marketplace': 'Твой маркетплейс',
        'product_categories': 'Категории товаров',
        'featured': '⭐ Рекомендуемые',
        'all_products_link': 'Все товары',
        'ai_promo_label': '🤖 AI-ассистент',
        'ai_promo_title': 'Не можешь найти нужное?',
        'ai_promo_text': 'Наш AI поможет с выбором, сравнит товары и даст персональные рекомендации.',
        'open_ai_chat': 'Открыть AI Чат →',
        'fast_delivery': '🚀 Быстрая доставка',
        'door_delivery': 'До двери за 24 часа',
        'free_from': 'Бесплатно при заказе от 1000₸',
        'order_now': 'Заказать сейчас',
        'new_arrivals': '🆕 Новинки',
        'all_new': 'Все новинки',
        'recommendations_for_you': '💡 Рекомендации для вас',
        'home': 'Главная',
        'search': 'Поиск',
        'filters': 'Фильтры',
        'price': 'Цена, ₸',
        'from_label': 'От',
        'to_label': 'До',
        'rating': 'Рейтинг',
        'any': 'Любой',
        'in_stock_only': 'Только в наличии',
        'apply': 'Применить',
        'reset_filters': 'Сбросить фильтры',
        'results_for': 'Результаты для',
        'products_count': 'товаров',
        'sort_new': 'Новинки',
        'sort_popular': 'По популярности',
        'sort_rating': 'По рейтингу',
    'sort_reviews': 'По отзывам',
    'sort_price_asc': 'Цена ↑',
    'sort_price_desc': 'Цена ↓',
    'pagination': 'Пагинация',
    'hours_24': '24ч',
    'card_networks': 'Visa, Mastercard, МИР',
    'form_labels': {
        'username': 'Email',
        'email': 'Email',
        'password': 'Пароль',
        'password1': 'Пароль',
        'password2': 'Повторите пароль',
        'first_name': 'Имя',
        'last_name': 'Фамилия',
        'phone': 'Телефон',
        'address': 'Адрес',
        'city': 'Город',
        'birth_date': 'Дата рождения',
        'avatar': 'Аватар',
        'full_name': 'Полное имя',
        'postal_code': 'Почтовый индекс',
        'title': 'Заголовок',
        'text': 'Отзыв',
        'pros': 'Достоинства',
        'cons': 'Недостатки',
    },
    'form_placeholders': {
        'username': 'Email',
        'email': 'Email',
        'password': 'Пароль',
        'password1': 'Пароль',
        'password2': 'Повторите пароль',
        'first_name': 'Имя',
        'last_name': 'Фамилия',
        'full_name': 'Иван Иванов',
        'phone': '+7 (999) 123-45-67',
        'city': 'Алматы',
        'address': 'ул. Пушкина, д. 1, кв. 1',
        'postal_code': '123456',
        'title': 'Заголовок отзыва',
        'text': 'Ваш отзыв...',
        'pros': 'Достоинства товара',
        'cons': 'Недостатки товара',
    },
    'dashboard': 'Дашборд',
    'dashboard_panel': 'Панель управления',
    'admin_panel': 'Admin Panel',
    'main': 'Основное',
    'users': 'Пользователи',
    'shop': 'Магазин ↗',
    'total': 'Всего',
    'search_button': 'Найти',
    'reset': 'Сбросить',
    'user': 'Пользователь',
    'spent': 'Потрачено',
    'registered': 'Зарегистрирован',
    'status': 'Статус',
    'staff': 'Персонал',
    'active': 'Активен',
    'blocked': 'Заблокирован',
    'open': 'Открыть →',
    'users_not_found': 'Пользователей не найдено',
    'page_short': 'Стр.',
    'page': 'Страница',
    'of': 'из',
    'buyer': 'Покупатель',
    'sum': 'Сумма',
    'date': 'Дата',
    'all': 'Все',
    'date_from': 'Дата от',
    'date_to': 'Дата до',
    'orders_not_found': 'Заказов не найдено',
    'category': 'Категория',
    'stock': 'Склад',
    'product': 'Товар',
    'low_stock_filter': 'Заканчивается (≤5)',
    'no_stock_short': 'нет',
    'low_stock_short': 'мало',
    'no_reviews_short': 'нет отзывов',
    'active_col': 'Активен',
    'products_not_found': 'Товаров не найдено',
    'stock_update_error': 'Ошибка обновления склада',
    'orders_today': 'Заказы сегодня',
    'month': 'За месяц',
    'revenue_today': 'Выручка сегодня',
    'new_users': 'Новые пользователи',
    'products_in_stock': 'Товары в стоке',
    'ending': 'Заканчивается',
    'pending_orders_alert': 'заказов ожидают обработки →',
    'pending_reviews_alert': 'отзывов на модерации →',
    'low_stock_alert': 'товаров заканчивается →',
    'revenue_14_days': 'Выручка за 14 дней',
    'order_statuses': 'Статусы заказов',
    'recent_orders': 'Последние заказы',
    'all_link': 'Все →',
    'top_products': 'Топ товаров',
    'no_data': 'Нет данных',
    'revenue_currency': 'Выручка ₸',
    'orders_chart': 'Заказов',
    'review_moderation': 'Модерация отзывов',
    'awaiting_review': 'ожидают проверки',
    'pending_review': 'На проверке',
    'approved_reviews': 'Одобренные',
    'approved': 'Одобрен',
    'approve': '✅ Одобрить',
    'unpublish': '⏸ Снять с публикации',
    'delete': '🗑 Удалить',
    'reviews_empty': 'Отзывов нет',
    'delete_review_confirm': 'Удалить отзыв?',
    'session': 'Сессия',
    'messages_count': 'Сообщений',
    'updated': 'Обновлён',
    'anonymous': 'Анонимный',
    'chats_empty': 'Чатов нет',
    'chat': 'Чат',
    'messages_empty': 'Сообщений нет',
    'order_status': 'Статус заказа',
    'change_status': 'Изменить статус',
    'save_status': 'Сохранить статус',
    'comment_example': 'Например: передан в службу доставки',
    'customer': 'Покупатель',
    'name': 'Имя',
    'created': 'Создан',
    'updated_at': 'Обновлён',
    'statistics': 'Статистика',
    'registration': 'Регистрация',
    'confirm_are_you_sure': 'Уверены?',
    'block_user': '🔒 Заблокировать',
    'unblock_user': '✅ Разблокировать',
    'total_lower': 'всего',
    'orders_empty_short': 'Заказов нет',
    'add_product': 'Добавить товар',
    'product_info': 'Информация о товаре',
    'product_description': 'Описание товара',
    'product_media_settings': 'Фото и настройки',
    'save_product': 'Сохранить товар',
    'cancel': 'Отмена',
    'product_form_labels': {
        'name': 'Название',
        'sku': 'Артикул',
        'category': 'Категория',
        'brand': 'Бренд',
        'price': 'Цена',
        'old_price': 'Старая цена',
        'stock': 'Остаток',
        'weight': 'Вес',
        'short_description': 'Краткое описание',
        'description': 'Полное описание',
        'main_image': 'Главное фото',
        'is_active': 'Активен',
        'is_featured': 'Рекомендуемый',
    },
    'order_status_labels': {
        'pending': 'Ожидает оплаты',
        'paid': 'Оплачен',
        'processing': 'В обработке',
        'shipped': 'Отправлен',
        'delivered': 'Доставлен',
        'cancelled': 'Отменён',
        'refunded': 'Возврат',
    },
        'back': '← Назад',
        'forward': 'Вперёд →',
        'nothing_found': 'Ничего не найдено',
        'try_change_query': 'Попробуйте изменить запрос или сбросить фильтры',
        'add_to_cart': 'В корзину',
        'out_of_stock': 'Нет в наличии',
    },
    'kk': {
        'free_delivery': '📦 5000₸ бастап тегін жеткізу',
        'working_hours': 'Дс-Жс 9:00–21:00',
        'search_placeholder': 'Тауарларды, брендтерді, санаттарды іздеу...',
        'ai_assistant': 'AI көмекші',
        'ai_chat': 'AI чат',
        'wishlist': 'Таңдаулылар',
        'cart': 'Себет',
        'profile': 'Профиль',
        'orders': 'Менің тапсырыстарым',
        'logout': 'Шығу',
        'login': 'Кіру',
        'all_products': 'Барлық тауарлар',
        'footer_about': 'Қазақстан бойынша жылдам жеткізілетін миллиондаған тауары бар ірі маркетплейс',
        'buyers': 'Сатып алушыларға',
        'catalog': 'Тауарлар каталогы',
        'company': 'Компания',
        'about': 'Біз туралы',
        'partners': 'Серіктестерге',
        'jobs': 'Бос орындар',
        'contacts': 'Байланыс',
        'support': 'Қолдау',
        'free_call': 'Тегін, Дс-Жс 9–21',
        'rights': '© 2026 YMarket. Барлық құқықтар қорғалған.',
        'privacy': 'Құпиялылық саясаты',
        'terms': 'Пайдаланушы келісімі',
        'home_title': 'Басты бет',
        'sale_badge': '🔥 -70% дейін үлкен жеңілдік',
        'hero_title_1': 'Қажеттінің бәрі',
        'hero_title_2': '— осында және қазір',
        'hero_text': 'Миллиондаған тауар, жылдам жеткізу, үздік бағалар. Керегіңізді AI көмекшімізбен табыңыз.',
        'view_catalog': 'Каталогты көру →',
        'ask_ai': '🤖 AI-дан сұрау',
        'products_short': 'тауар',
        'delivery_short': 'жеткізу',
        'buyers_short': 'сатып алушы',
        'your_marketplace': 'Сенің маркетплейсің',
        'product_categories': 'Тауар санаттары',
        'featured': '⭐ Ұсынылғандар',
        'all_products_link': 'Барлық тауарлар',
        'ai_promo_label': '🤖 AI көмекші',
        'ai_promo_title': 'Керегіңізді таба алмай жүрсіз бе?',
        'ai_promo_text': 'AI таңдауға көмектеседі, тауарларды салыстырады және жеке ұсыныстар береді.',
        'open_ai_chat': 'AI чатты ашу →',
        'fast_delivery': '🚀 Жылдам жеткізу',
        'door_delivery': 'Есікке дейін 24 сағатта',
        'free_from': '1000₸ бастап тегін',
        'order_now': 'Қазір тапсырыс беру',
        'new_arrivals': '🆕 Жаңалықтар',
        'all_new': 'Барлық жаңалықтар',
        'recommendations_for_you': '💡 Сізге ұсыныстар',
        'home': 'Басты бет',
        'search': 'Іздеу',
        'filters': 'Сүзгілер',
        'price': 'Баға, ₸',
        'from_label': 'Бастап',
        'to_label': 'Дейін',
        'rating': 'Рейтинг',
        'any': 'Кез келген',
        'in_stock_only': 'Тек бар тауарлар',
        'apply': 'Қолдану',
        'reset_filters': 'Сүзгілерді тазарту',
        'results_for': 'Нәтижелер',
        'products_count': 'тауар',
        'sort_new': 'Жаңалықтар',
        'sort_popular': 'Танымалдық бойынша',
        'sort_rating': 'Рейтинг бойынша',
    'sort_reviews': 'Пікірлер бойынша',
    'sort_price_asc': 'Баға ↑',
    'sort_price_desc': 'Баға ↓',
    'pagination': 'Беттер',
    'hours_24': '24сағ',
    'card_networks': 'Visa, Mastercard, MIR',
    'form_labels': {
        'username': 'Email',
        'email': 'Email',
        'password': 'Құпиясөз',
        'password1': 'Құпиясөз',
        'password2': 'Құпиясөзді қайталаңыз',
        'first_name': 'Аты',
        'last_name': 'Тегі',
        'phone': 'Телефон',
        'address': 'Мекенжай',
        'city': 'Қала',
        'birth_date': 'Туған күні',
        'avatar': 'Аватар',
        'full_name': 'Толық аты',
        'postal_code': 'Пошта индексі',
        'title': 'Тақырып',
        'text': 'Пікір',
        'pros': 'Артықшылықтары',
        'cons': 'Кемшіліктері',
    },
    'form_placeholders': {
        'username': 'Email',
        'email': 'Email',
        'password': 'Құпиясөз',
        'password1': 'Құпиясөз',
        'password2': 'Құпиясөзді қайталаңыз',
        'first_name': 'Аты',
        'last_name': 'Тегі',
        'full_name': 'Иван Иванов',
        'phone': '+7 (999) 123-45-67',
        'city': 'Алматы',
        'address': 'Пушкин көшесі, 1-үй, 1-пәтер',
        'postal_code': '123456',
        'title': 'Пікір тақырыбы',
        'text': 'Пікіріңіз...',
        'pros': 'Тауардың артықшылықтары',
        'cons': 'Тауардың кемшіліктері',
    },
    'dashboard': 'Дашборд',
    'dashboard_panel': 'Басқару панелі',
    'admin_panel': 'Admin Panel',
    'main': 'Негізгі',
    'users': 'Пайдаланушылар',
    'shop': 'Дүкен ↗',
    'total': 'Барлығы',
    'search_button': 'Іздеу',
    'reset': 'Тазарту',
    'user': 'Пайдаланушы',
    'spent': 'Жұмсалды',
    'registered': 'Тіркелген',
    'status': 'Статус',
    'staff': 'Қызметкер',
    'active': 'Белсенді',
    'blocked': 'Бұғатталған',
    'open': 'Ашу →',
    'users_not_found': 'Пайдаланушылар табылмады',
    'page_short': 'Бет',
    'page': 'Бет',
    'of': '/',
    'buyer': 'Сатып алушы',
    'sum': 'Сома',
    'date': 'Күн',
    'all': 'Барлығы',
    'date_from': 'Күннен',
    'date_to': 'Күнге дейін',
    'orders_not_found': 'Тапсырыстар табылмады',
    'category': 'Санат',
    'stock': 'Қойма',
    'product': 'Тауар',
    'low_stock_filter': 'Таусылып келеді (≤5)',
    'no_stock_short': 'жоқ',
    'low_stock_short': 'аз',
    'no_reviews_short': 'пікір жоқ',
    'active_col': 'Белсенді',
    'products_not_found': 'Тауарлар табылмады',
    'stock_update_error': 'Қойманы жаңарту қатесі',
    'orders_today': 'Бүгінгі тапсырыстар',
    'month': 'Ай ішінде',
    'revenue_today': 'Бүгінгі табыс',
    'new_users': 'Жаңа пайдаланушылар',
    'products_in_stock': 'Қоймадағы тауарлар',
    'ending': 'Таусылып келеді',
    'pending_orders_alert': 'тапсырыс өңдеуді күтуде →',
    'pending_reviews_alert': 'пікір модерацияда →',
    'low_stock_alert': 'тауар таусылып келеді →',
    'revenue_14_days': '14 күндегі табыс',
    'order_statuses': 'Тапсырыс статустары',
    'recent_orders': 'Соңғы тапсырыстар',
    'all_link': 'Барлығы →',
    'top_products': 'Үздік тауарлар',
    'no_data': 'Дерек жоқ',
    'revenue_currency': 'Табыс ₸',
    'orders_chart': 'Тапсырыстар',
    'review_moderation': 'Пікірлерді модерациялау',
    'awaiting_review': 'тексеруді күтеді',
    'pending_review': 'Тексеруде',
    'approved_reviews': 'Мақұлданған',
    'approved': 'Мақұлданды',
    'approve': '✅ Мақұлдау',
    'unpublish': '⏸ Жариялаудан алу',
    'delete': '🗑 Жою',
    'reviews_empty': 'Пікірлер жоқ',
    'delete_review_confirm': 'Пікірді жою керек пе?',
    'session': 'Сессия',
    'messages_count': 'Хабарламалар',
    'updated': 'Жаңартылды',
    'anonymous': 'Аноним',
    'chats_empty': 'Чаттар жоқ',
    'chat': 'Чат',
    'messages_empty': 'Хабарламалар жоқ',
    'order_status': 'Тапсырыс статусы',
    'change_status': 'Статусты өзгерту',
    'save_status': 'Статусты сақтау',
    'comment_example': 'Мысалы: жеткізу қызметіне берілді',
    'customer': 'Клиент',
    'name': 'Аты',
    'created': 'Жасалды',
    'updated_at': 'Жаңартылды',
    'statistics': 'Статистика',
    'registration': 'Тіркелу',
    'confirm_are_you_sure': 'Сенімдісіз бе?',
    'block_user': '🔒 Бұғаттау',
    'unblock_user': '✅ Бұғаттан шығару',
    'total_lower': 'барлығы',
    'orders_empty_short': 'Тапсырыс жоқ',
    'add_product': 'Тауар қосу',
    'product_info': 'Тауар туралы ақпарат',
    'product_description': 'Тауар сипаттамасы',
    'product_media_settings': 'Фото және баптаулар',
    'save_product': 'Тауарды сақтау',
    'cancel': 'Болдырмау',
    'product_form_labels': {
        'name': 'Атауы',
        'sku': 'Артикул',
        'category': 'Санат',
        'brand': 'Бренд',
        'price': 'Баға',
        'old_price': 'Ескі баға',
        'stock': 'Қалдық',
        'weight': 'Салмақ',
        'short_description': 'Қысқаша сипаттама',
        'description': 'Толық сипаттама',
        'main_image': 'Негізгі фото',
        'is_active': 'Белсенді',
        'is_featured': 'Ұсынылған',
    },
    'order_status_labels': {
        'pending': 'Төлем күтуде',
        'paid': 'Төленді',
        'processing': 'Өңделуде',
        'shipped': 'Жіберілді',
        'delivered': 'Жеткізілді',
        'cancelled': 'Болдырылмады',
        'refunded': 'Қайтарылды',
    },
        'back': '← Артқа',
        'forward': 'Алға →',
        'nothing_found': 'Ештеңе табылмады',
        'try_change_query': 'Сұрауды өзгертіп көріңіз немесе сүзгілерді тазалаңыз',
        'add_to_cart': 'Себетке',
        'out_of_stock': 'Қоймада жоқ',
    },
    'en': {
        'free_delivery': '📦 Free delivery from 5000₸',
        'working_hours': 'Mon-Sun 9:00–21:00',
        'search_placeholder': 'Search products, brands, categories...',
        'ai_assistant': 'AI Assistant',
        'ai_chat': 'AI Chat',
        'wishlist': 'Wishlist',
        'cart': 'Cart',
        'profile': 'Profile',
        'orders': 'My orders',
        'logout': 'Log out',
        'login': 'Log in',
        'all_products': 'All products',
        'footer_about': 'A large marketplace with millions of products and fast delivery across Kazakhstan',
        'buyers': 'For buyers',
        'catalog': 'Product catalog',
        'company': 'Company',
        'about': 'About us',
        'partners': 'Partners',
        'jobs': 'Jobs',
        'contacts': 'Contacts',
        'support': 'Support',
        'free_call': 'Free call, Mon-Sun 9–21',
        'rights': '© 2026 YMarket. All rights reserved.',
        'privacy': 'Privacy policy',
        'terms': 'Terms of use',
        'home_title': 'Home',
        'sale_badge': '🔥 Mega sale up to -70%',
        'hero_title_1': 'Everything you need',
        'hero_title_2': '— here and now',
        'hero_text': 'Millions of products, fast delivery, best prices. Find what you need with our AI assistant.',
        'view_catalog': 'View catalog →',
        'ask_ai': '🤖 Ask AI',
        'products_short': 'products',
        'delivery_short': 'delivery',
        'buyers_short': 'buyers',
        'your_marketplace': 'Your marketplace',
        'product_categories': 'Product categories',
        'featured': '⭐ Featured',
        'all_products_link': 'All products',
        'ai_promo_label': '🤖 AI assistant',
        'ai_promo_title': 'Can’t find what you need?',
        'ai_promo_text': 'Our AI helps you choose, compare products, and get personalized recommendations.',
        'open_ai_chat': 'Open AI Chat →',
        'fast_delivery': '🚀 Fast delivery',
        'door_delivery': 'To your door in 24 hours',
        'free_from': 'Free on orders from 1000₸',
        'order_now': 'Order now',
        'new_arrivals': '🆕 New arrivals',
        'all_new': 'All new arrivals',
        'recommendations_for_you': '💡 Recommended for you',
        'home': 'Home',
        'search': 'Search',
        'filters': 'Filters',
        'price': 'Price, ₸',
        'from_label': 'From',
        'to_label': 'To',
        'rating': 'Rating',
        'any': 'Any',
        'in_stock_only': 'In stock only',
        'apply': 'Apply',
        'reset_filters': 'Reset filters',
        'results_for': 'Results for',
        'products_count': 'products',
        'sort_new': 'New arrivals',
        'sort_popular': 'By popularity',
        'sort_rating': 'By rating',
    'sort_reviews': 'By reviews',
    'sort_price_asc': 'Price ↑',
    'sort_price_desc': 'Price ↓',
    'pagination': 'Pagination',
    'hours_24': '24h',
    'card_networks': 'Visa, Mastercard, MIR',
    'form_labels': {
        'username': 'Email',
        'email': 'Email',
        'password': 'Password',
        'password1': 'Password',
        'password2': 'Repeat password',
        'first_name': 'First name',
        'last_name': 'Last name',
        'phone': 'Phone',
        'address': 'Address',
        'city': 'City',
        'birth_date': 'Birth date',
        'avatar': 'Avatar',
        'full_name': 'Full name',
        'postal_code': 'Postal code',
        'title': 'Title',
        'text': 'Review',
        'pros': 'Pros',
        'cons': 'Cons',
    },
    'form_placeholders': {
        'username': 'Email',
        'email': 'Email',
        'password': 'Password',
        'password1': 'Password',
        'password2': 'Repeat password',
        'first_name': 'First name',
        'last_name': 'Last name',
        'full_name': 'John Smith',
        'phone': '+7 (999) 123-45-67',
        'city': 'Almaty',
        'address': '1 Pushkin St, apt. 1',
        'postal_code': '123456',
        'title': 'Review title',
        'text': 'Your review...',
        'pros': 'Product pros',
        'cons': 'Product cons',
    },
    'dashboard': 'Dashboard',
    'dashboard_panel': 'Dashboard',
    'admin_panel': 'Admin Panel',
    'main': 'Main',
    'users': 'Users',
    'shop': 'Shop ↗',
    'total': 'Total',
    'search_button': 'Search',
    'reset': 'Reset',
    'user': 'User',
    'spent': 'Spent',
    'registered': 'Registered',
    'status': 'Status',
    'staff': 'Staff',
    'active': 'Active',
    'blocked': 'Blocked',
    'open': 'Open →',
    'users_not_found': 'No users found',
    'page_short': 'Page',
    'page': 'Page',
    'of': 'of',
    'buyer': 'Buyer',
    'sum': 'Amount',
    'date': 'Date',
    'all': 'All',
    'date_from': 'Date from',
    'date_to': 'Date to',
    'orders_not_found': 'No orders found',
    'category': 'Category',
    'stock': 'Stock',
    'product': 'Product',
    'low_stock_filter': 'Low stock (≤5)',
    'no_stock_short': 'none',
    'low_stock_short': 'low',
    'no_reviews_short': 'no reviews',
    'active_col': 'Active',
    'products_not_found': 'No products found',
    'stock_update_error': 'Stock update error',
    'orders_today': 'Orders today',
    'month': 'This month',
    'revenue_today': 'Revenue today',
    'new_users': 'New users',
    'products_in_stock': 'Products in stock',
    'ending': 'Running low',
    'pending_orders_alert': 'orders awaiting processing →',
    'pending_reviews_alert': 'reviews awaiting moderation →',
    'low_stock_alert': 'products running low →',
    'revenue_14_days': 'Revenue for 14 days',
    'order_statuses': 'Order statuses',
    'recent_orders': 'Recent orders',
    'all_link': 'All →',
    'top_products': 'Top products',
    'no_data': 'No data',
    'revenue_currency': 'Revenue ₸',
    'orders_chart': 'Orders',
    'review_moderation': 'Review moderation',
    'awaiting_review': 'awaiting review',
    'pending_review': 'Pending',
    'approved_reviews': 'Approved',
    'approved': 'Approved',
    'approve': '✅ Approve',
    'unpublish': '⏸ Unpublish',
    'delete': '🗑 Delete',
    'reviews_empty': 'No reviews',
    'delete_review_confirm': 'Delete review?',
    'session': 'Session',
    'messages_count': 'Messages',
    'updated': 'Updated',
    'anonymous': 'Anonymous',
    'chats_empty': 'No chats',
    'chat': 'Chat',
    'messages_empty': 'No messages',
    'order_status': 'Order status',
    'change_status': 'Change status',
    'save_status': 'Save status',
    'comment_example': 'For example: handed to delivery service',
    'customer': 'Customer',
    'name': 'Name',
    'created': 'Created',
    'updated_at': 'Updated',
    'statistics': 'Statistics',
    'registration': 'Registration',
    'confirm_are_you_sure': 'Are you sure?',
    'block_user': '🔒 Block',
    'unblock_user': '✅ Unblock',
    'total_lower': 'total',
    'orders_empty_short': 'No orders',
    'add_product': 'Add product',
    'product_info': 'Product information',
    'product_description': 'Product description',
    'product_media_settings': 'Photo and settings',
    'save_product': 'Save product',
    'cancel': 'Cancel',
    'product_form_labels': {
        'name': 'Name',
        'sku': 'SKU',
        'category': 'Category',
        'brand': 'Brand',
        'price': 'Price',
        'old_price': 'Old price',
        'stock': 'Stock',
        'weight': 'Weight',
        'short_description': 'Short description',
        'description': 'Full description',
        'main_image': 'Main photo',
        'is_active': 'Active',
        'is_featured': 'Featured',
    },
    'order_status_labels': {
        'pending': 'Awaiting payment',
        'paid': 'Paid',
        'processing': 'Processing',
        'shipped': 'Shipped',
        'delivered': 'Delivered',
        'cancelled': 'Cancelled',
        'refunded': 'Refunded',
    },
        'back': '← Back',
        'forward': 'Forward →',
        'nothing_found': 'Nothing found',
        'try_change_query': 'Try changing your query or resetting filters',
        'add_to_cart': 'Add to cart',
        'out_of_stock': 'Out of stock',
    },
}

UI_TRANSLATIONS['ru'].update({
    'register_title': 'Регистрация',
    'create_account': 'Создать аккаунт',
    'join_buyers': 'Присоединяйтесь к миллионам покупателей',
    'create_account_btn': 'Создать аккаунт →',
    'already_have_account': 'Уже есть аккаунт?',
    'welcome': 'Добро пожаловать!',
    'login_subtitle': 'Войдите в свой аккаунт',
    'login_btn': 'Войти →',
    'no_account': 'Нет аккаунта?',
    'register_link': 'Зарегистрируйтесь',
    'my_profile': 'Мой профиль',
    'avatar_alt': 'Аватар',
    'member_since': 'На сайте с',
    'edit_profile': 'Редактировать профиль',
    'save_changes': 'Сохранить изменения',
    'wishlist_empty': 'В избранном пусто',
    'wishlist_empty_text': 'Добавляйте товары в избранное, нажав ♥ на карточке',
    'go_to_catalog': 'Перейти в каталог',
    'sku': 'Арт.',
    'remove': '🗑 Удалить',
    'summary': 'Итого',
    'items': 'Товары',
    'delivery': 'Доставка',
    'free': 'Бесплатно',
    'to_pay': 'К оплате',
    'free_delivery_left': '🚚 До бесплатной доставки:',
    'checkout_btn': 'Оформить заказ →',
    'continue_shopping': '← Продолжить покупки',
    'cart_empty': 'Корзина пуста',
    'cart_empty_text': 'Добавьте товары, которые вам понравились',
    'ai_help_choose': '🤖 AI поможет выбрать',
    'checkout_title': 'Оформление заказа',
    'checkout_step': 'Оформление',
    'confirmation_step': 'Подтверждение',
    'contact_details': '👤 Контактные данные',
    'delivery_address': '🚚 Адрес доставки',
    'comment_optional': 'Комментарий (необязательно)',
    'courier_info_placeholder': 'Дополнительная информация для курьера...',
    'payment_method': '💳 Способ оплаты',
    'online_card': '💳 Онлайн картой',
    'confirm_order': 'Подтвердить заказ →',
    'your_order': 'Ваш заказ',
    'order': 'Заказ',
    'order_placed': 'Оформлен',
    'cancel_order': 'Отменить заказ',
    'cancel_order_confirm': 'Отменить заказ?',
    'details': 'Подробнее',
    'orders_empty': 'Заказов пока нет',
    'orders_empty_text': 'Начните делать покупки прямо сейчас!',
    'status_history': 'История статусов',
    'recipient': 'Получатель',
    'phone': 'Телефон',
    'city': 'Город',
    'address': 'Адрес',
    'postal_code': 'Индекс',
    'cost': 'Стоимость',
    'order_success_title': 'Заказ оформлен',
    'order_success_heading': 'Заказ оформлен!',
    'order_number': 'Номер заказа:',
    'order_details': 'Детали заказа',
    'confirmation_sent': '📧 Подтверждение отправлено на',
    'track_order': 'Следить за заказом',
    'reviews_word': 'отзывов',
    'views_word': 'просмотров',
    'in_stock': 'В наличии',
    'pcs': 'шт.',
    'product_sku': 'Артикул',
    'free_delivery_from': 'Бесплатная доставка при заказе от 1000₸',
    'return_14': 'Возврат в течение 14 дней',
    'description': 'Описание',
    'attributes': 'Характеристики',
    'reviews': 'Отзывы',
    'pros': 'Достоинства:',
    'cons': 'Недостатки:',
    'no_reviews': 'Пока нет отзывов. Будьте первым!',
    'write_review': 'Написать отзыв',
    'publish_review': 'Опубликовать отзыв',
    'login_to_review': 'Войдите, чтобы оставить отзыв',
    'similar_products': 'Похожие товары',
    'chat_history': 'История чатов',
    'new_chat': '+ Новый чат',
    'ymarket_ai': 'YMarket AI Помощник',
    'online': 'Онлайн',
    'limited_mode': 'Ограниченный режим',
    'hello_ai': 'Привет! Я AI-помощник',
    'ai_intro': 'Помогу найти товары, расскажу о характеристиках и дам рекомендации',
    'found_products': 'Найденные товары',
    'chat_placeholder': 'Спросите что-нибудь о товарах... (Enter для отправки)',
    'ai_disclaimer': 'AI работает на Ollama · Ответы генерируются локально · Не является финансовым советом',
    'you_short': 'Я',
    'ai_error': '⚠️ Не удалось получить ответ. Попробуйте ещё раз.',
    'new_chat_started': 'Новый чат начат!',
    'ask_about_products': 'Спросите меня о товарах',
    'suggestions': ['Найти смартфон до 30000₸', 'Лучшие ноутбуки для работы', 'Подобрать подарок на день рождения', 'Сравнить наушники', 'Что популярно сейчас?'],
})

UI_TRANSLATIONS['kk'].update({
    'register_title': 'Тіркелу',
    'create_account': 'Аккаунт жасау',
    'join_buyers': 'Миллиондаған сатып алушыға қосылыңыз',
    'create_account_btn': 'Аккаунт жасау →',
    'already_have_account': 'Аккаунтыңыз бар ма?',
    'welcome': 'Қош келдіңіз!',
    'login_subtitle': 'Аккаунтыңызға кіріңіз',
    'login_btn': 'Кіру →',
    'no_account': 'Аккаунтыңыз жоқ па?',
    'register_link': 'Тіркеліңіз',
    'my_profile': 'Менің профилім',
    'avatar_alt': 'Аватар',
    'member_since': 'Сайтта тіркелген күні',
    'edit_profile': 'Профильді өңдеу',
    'save_changes': 'Өзгерістерді сақтау',
    'wishlist_empty': 'Таңдаулылар бос',
    'wishlist_empty_text': 'Тауар карточкасындағы ♥ белгісін басып, таңдаулыларға қосыңыз',
    'go_to_catalog': 'Каталогқа өту',
    'sku': 'Арт.',
    'remove': '🗑 Жою',
    'summary': 'Қорытынды',
    'items': 'Тауарлар',
    'delivery': 'Жеткізу',
    'free': 'Тегін',
    'to_pay': 'Төлеуге',
    'free_delivery_left': '🚚 Тегін жеткізуге дейін:',
    'checkout_btn': 'Тапсырысты рәсімдеу →',
    'continue_shopping': '← Сауданы жалғастыру',
    'cart_empty': 'Себет бос',
    'cart_empty_text': 'Ұнаған тауарларды қосыңыз',
    'ai_help_choose': '🤖 AI таңдауға көмектеседі',
    'checkout_title': 'Тапсырысты рәсімдеу',
    'checkout_step': 'Рәсімдеу',
    'confirmation_step': 'Растау',
    'contact_details': '👤 Байланыс деректері',
    'delivery_address': '🚚 Жеткізу мекенжайы',
    'comment_optional': 'Пікір (міндетті емес)',
    'courier_info_placeholder': 'Курьерге қосымша ақпарат...',
    'payment_method': '💳 Төлем әдісі',
    'online_card': '💳 Онлайн картамен',
    'confirm_order': 'Тапсырысты растау →',
    'your_order': 'Сіздің тапсырысыңыз',
    'order': 'Тапсырыс',
    'order_placed': 'Рәсімделді',
    'cancel_order': 'Тапсырысты болдырмау',
    'cancel_order_confirm': 'Тапсырысты болдырмайсыз ба?',
    'details': 'Толығырақ',
    'orders_empty': 'Әзірге тапсырыс жоқ',
    'orders_empty_text': 'Қазір сатып алуды бастаңыз!',
    'status_history': 'Статус тарихы',
    'recipient': 'Алушы',
    'phone': 'Телефон',
    'city': 'Қала',
    'address': 'Мекенжай',
    'postal_code': 'Индекс',
    'cost': 'Құны',
    'order_success_title': 'Тапсырыс рәсімделді',
    'order_success_heading': 'Тапсырыс рәсімделді!',
    'order_number': 'Тапсырыс нөмірі:',
    'order_details': 'Тапсырыс мәліметтері',
    'confirmation_sent': '📧 Растау жіберілді:',
    'track_order': 'Тапсырысты бақылау',
    'reviews_word': 'пікір',
    'views_word': 'қаралым',
    'in_stock': 'Қоймада бар',
    'pcs': 'дана',
    'product_sku': 'Артикул',
    'free_delivery_from': '1000₸ бастап тегін жеткізу',
    'return_14': '14 күн ішінде қайтару',
    'description': 'Сипаттама',
    'attributes': 'Сипаттамалар',
    'reviews': 'Пікірлер',
    'pros': 'Артықшылықтары:',
    'cons': 'Кемшіліктері:',
    'no_reviews': 'Әзірге пікір жоқ. Бірінші болыңыз!',
    'write_review': 'Пікір жазу',
    'publish_review': 'Пікірді жариялау',
    'login_to_review': 'Пікір қалдыру үшін кіріңіз',
    'similar_products': 'Ұқсас тауарлар',
    'chat_history': 'Чат тарихы',
    'new_chat': '+ Жаңа чат',
    'ymarket_ai': 'YMarket AI көмекші',
    'online': 'Онлайн',
    'limited_mode': 'Шектеулі режим',
    'hello_ai': 'Сәлем! Мен AI көмекшімін',
    'ai_intro': 'Тауар табуға, сипаттамаларды түсіндіруге және ұсыныстар беруге көмектесемін',
    'found_products': 'Табылған тауарлар',
    'chat_placeholder': 'Тауарлар туралы сұраңыз... (жіберу үшін Enter)',
    'ai_disclaimer': 'AI Ollama арқылы жұмыс істейді · Жауаптар жергілікті жасалады · Қаржылық кеңес емес',
    'you_short': 'Мен',
    'ai_error': '⚠️ Жауап алу мүмкін болмады. Қайталап көріңіз.',
    'new_chat_started': 'Жаңа чат басталды!',
    'ask_about_products': 'Маған тауарлар туралы сұрақ қойыңыз',
    'suggestions': ['30000₸ дейін смартфон табу', 'Жұмысқа арналған үздік ноутбуктер', 'Туған күнге сыйлық таңдау', 'Құлаққаптарды салыстыру', 'Қазір не танымал?'],
})

UI_TRANSLATIONS['en'].update({
    'register_title': 'Register',
    'create_account': 'Create account',
    'join_buyers': 'Join millions of buyers',
    'create_account_btn': 'Create account →',
    'already_have_account': 'Already have an account?',
    'welcome': 'Welcome!',
    'login_subtitle': 'Log in to your account',
    'login_btn': 'Log in →',
    'no_account': 'No account?',
    'register_link': 'Sign up',
    'my_profile': 'My profile',
    'avatar_alt': 'Avatar',
    'member_since': 'Member since',
    'edit_profile': 'Edit profile',
    'save_changes': 'Save changes',
    'wishlist_empty': 'Your wishlist is empty',
    'wishlist_empty_text': 'Add products to your wishlist by pressing ♥ on a card',
    'go_to_catalog': 'Go to catalog',
    'sku': 'SKU',
    'remove': '🗑 Remove',
    'summary': 'Summary',
    'items': 'Items',
    'delivery': 'Delivery',
    'free': 'Free',
    'to_pay': 'To pay',
    'free_delivery_left': '🚚 Free delivery left:',
    'checkout_btn': 'Checkout →',
    'continue_shopping': '← Continue shopping',
    'cart_empty': 'Your cart is empty',
    'cart_empty_text': 'Add products you like',
    'ai_help_choose': '🤖 AI can help choose',
    'checkout_title': 'Checkout',
    'checkout_step': 'Checkout',
    'confirmation_step': 'Confirmation',
    'contact_details': '👤 Contact details',
    'delivery_address': '🚚 Delivery address',
    'comment_optional': 'Comment (optional)',
    'courier_info_placeholder': 'Additional information for the courier...',
    'payment_method': '💳 Payment method',
    'online_card': '💳 Online card payment',
    'confirm_order': 'Confirm order →',
    'your_order': 'Your order',
    'order': 'Order',
    'order_placed': 'Placed',
    'cancel_order': 'Cancel order',
    'cancel_order_confirm': 'Cancel order?',
    'details': 'Details',
    'orders_empty': 'No orders yet',
    'orders_empty_text': 'Start shopping now!',
    'status_history': 'Status history',
    'recipient': 'Recipient',
    'phone': 'Phone',
    'city': 'City',
    'address': 'Address',
    'postal_code': 'Postal code',
    'cost': 'Cost',
    'order_success_title': 'Order placed',
    'order_success_heading': 'Order placed!',
    'order_number': 'Order number:',
    'order_details': 'Order details',
    'confirmation_sent': '📧 Confirmation sent to',
    'track_order': 'Track order',
    'reviews_word': 'reviews',
    'views_word': 'views',
    'in_stock': 'In stock',
    'pcs': 'pcs.',
    'product_sku': 'SKU',
    'free_delivery_from': 'Free delivery on orders from 1000₸',
    'return_14': 'Returns within 14 days',
    'description': 'Description',
    'attributes': 'Attributes',
    'reviews': 'Reviews',
    'pros': 'Pros:',
    'cons': 'Cons:',
    'no_reviews': 'No reviews yet. Be the first!',
    'write_review': 'Write a review',
    'publish_review': 'Publish review',
    'login_to_review': 'Log in to leave a review',
    'similar_products': 'Similar products',
    'chat_history': 'Chat history',
    'new_chat': '+ New',
    'ymarket_ai': 'YMarket AI Assistant',
    'online': 'Online',
    'limited_mode': 'Limited mode',
    'hello_ai': 'Hi! I am your AI assistant',
    'ai_intro': 'I can help find products, explain specs, and suggest options',
    'found_products': 'Found products',
    'chat_placeholder': 'Ask something about products... (Enter to send)',
    'ai_disclaimer': 'AI runs on Ollama · Answers are generated locally · Not financial advice',
    'you_short': 'You',
    'ai_error': '⚠️ Could not get a response. Please try again.',
    'new_chat_started': 'New chat started!',
    'ask_about_products': 'Ask me about products',
    'suggestions': ['Find a smartphone under 30000₸', 'Best laptops for work', 'Pick a birthday gift', 'Compare headphones', 'What is popular now?'],
})


def categories_ctx(request):
    categories = Category.objects.filter(is_active=True, parent=None).prefetch_related('children')
    return {'nav_categories': categories}


def ui_translations(request):
    language = getattr(request, 'LANGUAGE_CODE', 'ru') or 'ru'
    language = language.split('-')[0]
    return {'ui': UI_TRANSLATIONS.get(language, UI_TRANSLATIONS['ru'])}
