# Generated by Django 5.2.11 on 2026-02-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_chat', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='mentioned_products',
            field=models.ManyToManyField(blank=True, related_name='chat_mentions', to='products.product'),
        ),
    ]
